services:
  nyt-letter-boxed:
    build: .
    container_name: nyt-letter-boxed
    networks:
      - nginxproxymanager_default
    volumes:
      - ./logs:/app/logs
    restart: always

networks:
  nginxproxymanager_default:
    external: true